[package]
name = "Frostify"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.9"
wgpu = "24.0.1"
tokio = { version = "1.28", features = ["full"] }
bytemuck = { version = "1.13", features = ["derive"] }
pollster = "0.4.0"
image = "0.25.5"

# [target.'cfg(target_os = "windows")'.dependencies]
# winapi = { version = "0.3.9", default-features = false, features = ["minwindef", "dwmapi"] }