[package]
name = "Frostify"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
winit = "0.30.11"
wgpu = { version = "25.0.2", features = ["noop"] }
tokio = { version = "1.45.1", features = ["full"] }
bytemuck = { version = "1.23.1", features = ["derive"] }
pollster = "0.4.0"
image = "0.25.6"
cosmic-text = "0.14.2"
uuid = { version = "1.17.0", features = ["v4", "fast-rng"] }
log = "0.4.27"
env_logger = "0.11.8"
time = { version = "0.3.41", features = [
    "formatting",
    "macros",
    "local-offset",
] }
colored = "3.0.0"
palette = { version = "0.7.6", features = ["named", "wide"] }
oauth2 = { version = "5.0.0", features = ["rustls-tls"] }
reqwest = { version = "0.12.20", features = ["json", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
webbrowser = "1.0.5"
base64 = "0.22.1"
sha2 = "0.10.9"
rand = "0.9.1"
url = "2.5.4"
keyring = { version = "3.6.2", features = [
    "windows-native",
    "apple-native",
    "linux-native",
] }
clap = { version = "4.5.40", features = ["derive"] }
librespot = "0.6.0"
strum = "0.27.1"
strum_macros = "0.27.1"

# Derive crate for Frostify
frostify_derive = { path = "./frostify_derive" }

[features]
console = []

[build-dependencies]
winresource = "0.1.22"
