[package]
name = "Frostify"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
winit = "0.30.9"
wgpu = "24.0.3"
tokio = { version = "1.44.1", features = ["full"] }
bytemuck = { version = "1.22.0", features = ["derive"] }
pollster = "0.4.0"
image = "0.25.5"
glyphon = "0.8.0"
uuid = { version = "1.16.0", features = ["v4","fast-rng"] }
log = "0.4.26"
env_logger = "0.11.7"
time = { version = "0.3.40", features = ["formatting", "macros", "local-offset"] }
colored = "3.0.0"
colorgrad = "0.7.0"
oauth2 = { version = "5.0.0", features = ["rustls-tls"] }
reqwest = { version = "0.12.15", features = ["json", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
webbrowser = "1.0.4"
base64 = "0.22.1"
sha2 = "0.10.8"
rand = "0.9.0"
url = "2.5.4"
keyring = { version = "3.6.2", features = ["windows-native"] }

[build-dependencies]
winresource = "0.1.20"
