[package]
name = "Frostify"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
winit = "0.30.9"
wgpu = { version = "25.0.0", features = ["noop"] }
tokio = { version = "1.44.2", features = ["full"] }
bytemuck = { version = "1.22.0", features = ["derive"] }
pollster = "0.4.0"
image = "0.25.6"
glyphon = "0.9.0"
uuid = { version = "1.16.0", features = ["v4", "fast-rng"] }
log = "0.4.27"
env_logger = "0.11.8"
time = { version = "0.3.41", features = [
    "formatting",
    "macros",
    "local-offset",
] }
colored = "3.0.0"
colorgrad = "0.7.1"
oauth2 = { version = "5.0.0", features = ["rustls-tls"] }
reqwest = { version = "0.12.15", features = ["json", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
webbrowser = "1.0.4"
base64 = "0.22.1"
sha2 = "0.10.8"
rand = "0.9.1"
url = "2.5.4"
keyring = { version = "3.6.2", features = [
    "windows-native",
    "apple-native",
    "linux-native",
] }
smaa = { git = "https://github.com/yashs662/smaa-rs.git" }
clap = { version = "4.5.37", features = ["derive"] }
librespot = "0.6.0"

[build-dependencies]
winresource = "0.1.20"
